### PR TITLE
feat: updated ramsey/uuid to v4

### PR DESCRIPTION
**Pull request by daviddeng2100**
In order to upgrade Laravel to 8, we need to upgrade ramsey/uuid to version 4

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by daviddeng2100** [comment]
> Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.
> 
> Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @daviddeng2100 has signed the Contributor License Agreement. Thanks so much.

**Review by paulboocock — APPROVED** [review]
LGTM. Thanks for the PR!

We will include this in the next release which I'll try to get done in January for you, got to balance this with a few other things.

**Comment by sanysm** [comment]
When can we expect the next release?

**Comment by paulboocock** [comment]
It's scheduled for a february release, and work on the next release should begin next week.

**Comment by adatzer** [comment]
Thank you @daviddeng2100 ! 
Included in #91. Closing.

**Pull request closed without merging**
