### PR TITLE
Allow page URL to be set on the Subject

### PR DESCRIPTION
**Pull request by smugkarl**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Many thanks! Have you signed our CLA? https://github.com/snowplow/snowplow/wiki/CLA

**Comment by smugkarl** [comment]
The CLA has now been signed by SmugMug (for which I made this change).

**Comment by alexanderdean** [comment]
Hi @smugkarl - I just checked the entry. It looks good but alas the GitHub account names are wrong - the contributors are listed as having `smugmug` as your username, instead of `smugkarl` etc. Can you ask your Controller to fix?

**Comment by smugkarl** [comment]
Unfortunately, he just went on vacation.

**Comment by oguzhanunlu** [comment]
Hi @smugkarl , it's been a long time but in case you're still interested, we're planning to finalize `0.3.0` soon and can incorporate your work into the release if you fix the CLA issue.

**Comment by oguzhanunlu** [comment]
Closing as this is already introduced within #75 .

**Pull request closed without merging**
