### PR TITLE
Add page url & refr setters to Subject

### PR DESCRIPTION
**Pull request by grinderrz**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Cool! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by grinderrz** [comment]
Signed CLA.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much.

**Comment by oguzhanunlu** [comment]
Closing as this work is incorporated into the release branch, #75 . Thanks @grinderrz for the contribution!

**Pull request closed without merging**
