### PR TITLE
Switch dependency for hash generation to: webparser/laravel-uuid. 

### PR DESCRIPTION
**Pull request by smentek**
Implemented as switchable adapter with default value initialized during object construction.

### CODE REVIEW

**Comment by alexanderdean** [comment]
I like it! Can you sign our CLA please: https://github.com/snowplow/snowplow/wiki/CLA

**Comment by smentek** [comment]
I'm happy you like it. 
I've signed "Software Grant and Corporate Contributor License Agreement v1.0" for you.

**Comment by alexanderdean** [comment]
Confirmed! Thanks so much

**Comment by smentek** [comment]
Could you please give time estimation when new release with #53 will be created? We need to deploy, and If we know that you need more time I will go with forked version until official is ready...

**Comment by alexanderdean** [comment]
Hi @smentek - I don't have a time estimate now but I can tell you it's low priority in our unplanned work queue, so yes please go head and deploy with your forked version till ready.

**Comment by skynet** [comment]
is this going to make it to https://github.com/snowplow/snowplow-php-tracker soon?

**Comment by alexanderdean** [comment]
Hey @skynet - thanks for the heads-up. We don't have a timeline on this yet but we will try and get to this soon.

**Comment by skynet** [comment]
I wonder if I can just work with @smentek 's fork in the meantime. Thanks.

**Comment by 0x13a** [comment]
Hi @alexanderdean do you have any update on this? We are having issues with 
```
Package rhumsaa/uuid is abandoned, you should avoid using it. Use ramsey/uuid instead.
```

Hope this will get to the new release soon,

Thanks

**Comment by alexanderdean** [comment]
Have you tried using the 0.3.0-rc1 @0x13a?

**Comment by oguzhanunlu** [comment]
Hi @smentek , `0.3.0` will be finalized soon and a switch from `rhumsaa/uuid` to `ramsey/uuid` is included there, see #75 . Please renew your PR if you're still interested in this change.

**Pull request closed without merging**
