### PR TITLE
Prevent deprecation warning for dynamic property creation under PHP 8.2.

### PR DESCRIPTION
**Pull request by ldebrouwer**
See issue #123.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by ldebrouwer** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @ldebrouwer has signed the Contributor License Agreement. Thanks so much.

**Comment by mscwilson** [comment]
Hi @ldebrouwer, thanks so much for the PR. I discovered more deprecation warnings when I went to test this, so I've cherrypicked your commit into a new PR #128 with some other changes. We're aiming to release v0.6.0 this week.

**Pull request closed without merging**
