### PR TITLE
🍽 improve the find out more table

### PR DESCRIPTION
**Pull request by bradgarropy**
I fixed some incorrect Markdown links, centered the table items, and moved the links into the header.  
I hope you like it!

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by bradgarropy** [comment]
I signed it!


Brad Garropy

📱  817-266-5629

🏠 bradgarropy.com

**Comment by snowplowcla** [comment]
Confirmed! @bradgarropy  has signed the Individual Contributor License Agreement. Thanks so much

**Comment by oguzhanunlu** [comment]
Thanks @bradgarropy , we'll include your contribution in the upcoming `0.3.0` release.

**Comment by oguzhanunlu** [comment]
Closing the PR since we incorporated the work into #75 .
Thanks again @bradgarropy , your contribution is cherry-picked into the release branch.

**Pull request closed without merging**
