### PR TITLE
Update all copyright notices (close #113)

### LINKED ISSUE #113: Update all copyright notices
The Copyright Notice at the bottom of the [LICENSE file](https://github.com/snowplow/snowplow-php-tracker/blob/530ba8f8d76ade19cb6ce4cbd996df6c2fbc62b6/LICENSE-2.0.txt#L190
) is missing. It should look something like this: https://github.com/snowplow/snowplow-gtm-server-side-client/blob/main/LICENSE#L189

Also, we should update all the copyright headers (in source files):
` * Copyright (c) 2014-2021 Snowplow Analytics Ltd. All rights reserved.`
To:
` * Copyright (c) 2014-2022 Snowplow Analytics Ltd. All rights reserved.`

### PR DESCRIPTION
**Pull request by greg-el**
#113

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by matus-tomlein** [comment]
Screenshot 2022-02-04 at 17 01 30

I don't understand these copyright headers, but for some reason there is the year twice in each header? 🤔

**Comment by AlexBenny** [comment]
Weird, IMO we could keep the first line and remove the one after the Author.
It seems the trackers have all slightly different headers.

**Comment by matus-tomlein** [comment]
Suggested edit:
```diff
diff --git a/README.md b/README.md
--- README.md
+++ README.md
@@ -32,9 +32,9 @@
 | ![i1][techdocs-image]          | ![i2][setup-image]       | ![i3][contributing-image]        |
 
 ## Copyright and license
 
-The Snowplow PHP Tracker is copyright 2014-2021 Snowplow Analytics Ltd.
+The Snowplow PHP Tracker is copyright 2014-2022 Snowplow Analytics Ltd.
 
 Licensed under the **[Apache License, Version 2.0][license]** (the "License");
 you may not use this software except in compliance with the License.
 

```

**Review by matus-tomlein — APPROVED** [review]
LGTM!

**Pull request merged**
