### PR TITLE
Release/0.4.1

### PR DESCRIPTION
**Pull request by greg-el**
- #98 
- #99

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Review by matus-tomlein — CHANGES_REQUESTED** [review]
I think the code looks good, don't see any problems with that!

The only thing that I think deserves a bit of a clean up are the commits. This will be a bit painful (sorry), but I think it'd be good to take these steps:

1. Create issues for each of the PRs. Just use the same names as the PRs, title is enough.
2. Checkout this release branch locally and run interactive rebase in Git until the commit from the master branch
  - choose to reword the two issue commits and add (close #XXX) after the commit (remove any existing PR references) where XXX will be the issue numbers that the commits address
3. You should end up with only 2 commits addressing the issues (the Merge commit should disappear). If this is the case, you can `git push -f` the release branch to this PR.

Let me know if the above steps don't work as I imagine them to.

I tried to build the project and run tests using the [docker-compose scripts in quickstart](https://github.com/snowplow/snowplow-php-tracker#quickstart--testing) and got into a rabbit hole of problems. First, had to update the [hash for downloaded composer script](https://github.com/snowplow/snowplow-php-tracker/blob/master/Dockerfile#L12) as that has changed in the meantime. Next, some packages couldn’t download and had to bump their versions (in the end I also had to bump PHP to 7.4). Finally, when I managed to build the package, the tests that used the fake HTTP endpoint failed. Still trying to fix that. I think it would be good to fix the build for this version (I know that the Github Actions build works, but that is using an older setup). I will try to make it work for me locally and open a PR for you to check. Or I’ll give up in tears.

As a sidenote, we shouldn't forget about updating the official docs as there are a few changes to the APIs here.

**Comment by paulboocock** [comment]
After reading the comments from @matus-tomlein a couple of other things come to mind:

- Considering the [PHP Supported Versions](https://www.php.net/supported-versions.php) we could drop support for anything <7.4 in this release. Anyone using <7.4 should remain on 0.4.0.
- Ensure this works in PHP 8.0 and 8.1.
- Update the Github Action to build and test against 7.4, 8.0 and 8.1.
- Update this to 0.5.0 as it's an additive change so should be a MINOR release as per [semver](https://semver.org/).

**Comment by matus-tomlein** [comment]
Found out that there were 2 problems with the docker-compose build:

1. The Dockerfile checks hash for composer script that it downloads over the internet. The script has changed and so its hash changed too. I updated the hash and created a [tiny PR for it](https://github.com/snowplow/snowplow-php-tracker/pull/103)
2. The second problem with building the tracker and running tests happens only on ARM Macs (typical). Some of the dependencies do not support ARM Macs and need to be bumped. I managed to get it to work, but I don't think this is something that we need to add to this release. We can hold onto it a bit more since it also requires updating the PHP version.

So my suggestion for this release is that we:

1. fix the commit names in this release PR (as explained above), and
2. merge the small PR with updated composer hash.

**Comment by paulboocock** [comment]
I think we can include the dependency bumps here as we should be going to 0.5.0 anyway. It's always a good idea to take the opportunity of updating a tracker to bump the dependencies.

**Comment by AlexBenny** [comment]
Jumping in only with a quick note about the workflow. We set the guidelines here for external contributions and publishing: https://snplow.atlassian.net/wiki/spaces/DVR/pages/2775121921/Tracker+contribution#When-we-import-a-PR-of-an-external-contributor
I think that should be the reference for all the trackers, if it doesn't suit some cases we can always edit it.
The section about contribution is completely new so I'm not sure it works 100%, we can always discuss it and change it if there are problems.

**Comment by greg-el** [comment]
Superseded by https://github.com/snowplow/snowplow-php-tracker/pull/112

**Pull request closed without merging**
