### PR TITLE
Add a default timeout to curl and a custom log dir

### PR DESCRIPTION
**Pull request by dbhynds**
We've been using a fork of this package for a while. I figured it's worth opening up a PR for the changes. This PR:

- Adds a default timeout to CURL requests to prevent long-running requests from blocking the thread
- Adds the ability to specify a custom logs directory on the file emitter

For the timeout, we had issues where the service being called by the `CurlEmitter` was experiencing high latency. This is a resiliency measure that allows us to terminate slow requests and avoid high latency in another system from causing latency issues in our application.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by dbhynds** [comment]
I signed it!

**Comment by snowplowcla** [comment]
Confirmed! @dbhynds has signed the Contributor License Agreement. Thanks so much.

**Comment by matus-tomlein** [comment]
Thanks for the contribution @dbhynds! It looks good, but I would like to make two small adjustments:

1. separate the two changes in different PRs.
2. change the default timeout for curl while keeping it configurable.

I will cherry pick your commits and make the changes. Thanks again for the PR!

**Pull request closed without merging**
